### ISSUE TITLE
Pacman File Spawn

### ISSUE THREAD

**Issue by GameCrazed** [GameCrazed/SEGP2_PacmanApp#10]
Create a spawn point (called 'm') within the procedural generation file for pacman. There only needs to be one.

**Comment by Yahya-Said** [comment]
This task is completed. I used the randInt() method to choose a random line in the maze. Once chosen, i used a for loop to iterate though every element in the line. If the element at that position was a 'p' as in pellet, the location of the pellet was stored in another array. Now another random number was generated between 0 and the length of the array storing the pellets. This random number chooses a random index for us to overwrite with an 'm'. If the random line chosen contained no 'p', then a new random number is generated for the line. This ensures that one 'm' is always printed in the maze.

Edit: There was actually an error in the previous code as it could sometimes place you inside of wall blocks thus not allowing you to move. The problem has now been resolved in the newest version of the random generation class and will be released shortly.
