### ISSUE TITLE
Random Generation

### ISSUE THREAD

**Issue by GameCrazed** [GameCrazed/SEGP2_PacmanApp#8]
A generator needs to be implemented that can be called by the application so that it generates a procedurally rendered game level. This can then be used by the game to create the level that the player interacts with.

**Comment by GameCrazed** [comment]
Various improvements and features have been added to the random generation courtesy of Yahya, Includes host spawn location and more path like mazing as opposed to earlier versions.

**Comment by Yahya-Said** [comment]
The latest version of the random generator includes new characters (not game characters but letters for example 'e') for the four different types of ghosts. It also reduces the size of the maze to make it more playable. Choosing a random position for pacman every time the maze is loaded is also included. Further changes may be needed so this issue will stay opened
